### ISSUE TITLE
Getting Started Style transfer Not Available

### ISSUE THREAD

**Issue by Illioran** [kevinash/awesome-ai#1]
Hello,

I just started reading your book and I'm couldn't access the colab "Getting Started - Style Transfer", section 2.2.

Best regards,
![image](https://user-images.githubusercontent.com/74426090/117000091-d5875500-ace0-11eb-91d7-18f5fef1e996.png)

On the image, the french part say : Files not found

**Comment by kevinash** [comment]
Thanks! As an alternative, try downloading the repository and open/upload files to Colab https://github.com/kevinash/awesome-ai/blob/main/notebooks/1_GettingStarted/StyleTransfer_PyTorch.ipynb  (notebooks have a button Open with Colab), you can also import them in Colab as files (or save on your Google Drive). Sometimes that works better for Colab than opening directly from Github.
